#### Numpy: package for Multidimensional array

In [3]:
import numpy as np

In [4]:
simple_list=[2,5,7]
np.array(simple_list)

array([2, 5, 7])

In [5]:
arr=np.array([8,5,2])
arr

array([8, 5, 2])

In [6]:
arr

array([8, 5, 2])

In [7]:
list_of_lists=[[2,3,4],[5,6,7],[8,9,1]]
np.array(list_of_lists)

array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 1]])

In [8]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [9]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [10]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [21]:
np.zeros((1,5),int)

array([[0, 0, 0, 0, 0]])

In [22]:
np.ones((1,5),int)

array([[1, 1, 1, 1, 1]])

In [25]:
np.linspace(1,3,6)  ### lin => linear    

array([1. , 1.4, 1.8, 2.2, 2.6, 3. ])

In [26]:
np.linspace(5,80,3)

array([ 5. , 42.5, 80. ])

In [28]:
np.eye(5)  ## idnetical matrixx

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
np.random.rand(2,8)  ## uniform distribution

array([[0.36198086, 0.39197606, 0.15165928, 0.16188418, 0.59375804,
        0.29951501, 0.59487468, 0.25419357],
       [0.64411236, 0.40723778, 0.46197275, 0.06689495, 0.96820464,
        0.97386592, 0.86309707, 0.20303764]])

In [37]:
np.random.randn(2,5) ## bpoth + and -


array([[-1.74017501, -0.88115542, -1.14142001, -0.84388466, -0.74405975],
       [-0.81099015,  1.00616156,  0.0423753 ,  1.88194398,  1.16851516]])

In [38]:
np.random.randint(20,50,4)

array([47, 38, 34, 34])

In [14]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [15]:
rand_array=np.random.randint(0,100,10)
rand_array

array([62,  7, 10, 30, 49, 50, 29, 83, 42, 80])

In [16]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [17]:
sample_array.reshape(2,4)

ValueError: cannot reshape array of size 30 into shape (2,4)

In [18]:
rand_array.max()

83

In [50]:
rand_array.argmax()

0

In [20]:
a=np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
a.T ## T=> transpose

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
a=np.random.rand(2,3)  ## uniform with 2 rows and 3 column
a

array([[0.18116452, 0.35594211, 0.60957013],
       [0.54331526, 0.23738283, 0.1468599 ]])

In [56]:
a.T     #### Transpose

array([[0.87966772, 0.49225891],
       [0.50010364, 0.24449959],
       [0.51225732, 0.66440753]])

In [58]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [59]:
sample_array[0]

10

In [60]:
sample_array[2:5]

array([12, 13, 14])

In [62]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [64]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [65]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [67]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [68]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

### Two dimensional array

In [70]:
sample_matrix=np.array(([50,20,1,23],[24,23,21,33],[56,76,24,4]))
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  4]])

In [71]:
sample_matrix[1,2]

21

In [74]:
sample_matrix[2,:]

array([56, 76, 24,  4])

In [75]:
sample_matrix[2]

array([56, 76, 24,  4])

In [76]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 4, 24]])

#### selection techniques

In [78]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [79]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [81]:
np.exp(sample_array)   # exponential

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [82]:
np.sqrt(sample_array) #  square root

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [83]:
np.log(sample_array) # log value

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [84]:
np.max(sample_array)

19

In [86]:
np.min(sample_array)

1

In [87]:
np.argmax(sample_array)

18

In [89]:
np.argmin(sample_array)

0

In [90]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [91]:
np.std(sample_array)   ### standard deviation

5.477225575051661

In [92]:
np.var(sample_array)

30.0

In [93]:
np.mean(sample_array)

10.0

In [24]:
array=np.random.randn(3,4)
array

array([[ 0.31446718, -0.57300502,  0.03930968, -0.16245666],
       [-0.9833686 ,  0.47250189, -0.11028141,  0.25327789],
       [ 0.31985627,  0.49257576, -0.64082088,  0.17714525]])

In [28]:
np.round(array,decimals=3)    ## input digit after decimal

array([[ 0.314, -0.573,  0.039, -0.162],
       [-0.983,  0.473, -0.11 ,  0.253],
       [ 0.32 ,  0.493, -0.641,  0.177]])

In [101]:
sports=np.array(['golf','cricket','fball','cricket'])
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')

In [104]:
animals=np.array(['lion','cat','dog','lion'])
np.unique(animals)

array(['cat', 'dog', 'lion'], dtype='<U4')